id: P793CD0CC
initial_creation_type: input
source_metadata:
  title: Amitāyus Series
  language: bo
  description: 'Texts related to Amitāyus (tshe dpag med), the Buddha of Boundless
    Life:'
  volume:
    a4be22cd5e254cf7bf5ce6ca8cb5de47:
      title: 'The Bestowal of Supreme Immortality: A Prayer to the Lineage of Mitrayogin’s
        White and Red Amitāyus'
      parent: Lineage Prayers
    04a9f717937c4cacb07eaa1b09df09f4:
      title: A Prayer to Amitāyus
      parent: Prayers
    c34a8df16c834ac6818fa712792d19dd:
      title: A Daily Long-Life Practice of Amitāyus
      parent: Sādhanas
    df5bfa6550d644eb81bd635e059beffc:
      title: 'The Sublime Path to Immortality: The Quintessence of Profoundly Secret
        Pith Instructions on Attaining Vajra Longevity'
      parent: Sādhanas
    5f4d2ddd5e3344ccaca11b455a8e7e5b:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Sādhanas
    dc474929b08641cd94050d669a7acc47:
      title: Extemporary Practice of Longevity for Oneself or Others
      parent: Sādhanas
    c8d0e2c1e9cc4ec59ce18f399332959a:
      title: The Dhāraṇī of Amitāyus
      parent: Sūtra
    379d000bede242f1bf6db8b3928823a5:
      title: The Sūtra of Boundless Life and Wisdom
      parent: Sūtra
    daf0f11af70e40debc9abc7edfde18dc:
      title: How to Recite the Dhāraṇīsūtra of Amitāyus
      parent: Sūtra
created_at: '2022-03-01T02:43:20.957908'
last_modified_at: '2022-03-01T02:43:20.957910'
statistics:
  total_words: 8502
  total_non_words: 1659
quality:
  non_words_ratio: 0.2
